services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0173794628
      POSTGRES_DB: jaystaurant
    ports:
      - 5432:5432  

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080